/// Flutter icons AdvisorIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AdvisorIcons
///      fonts:
///       - asset: fonts/AdvisorIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AdvisorIcons {
  AdvisorIcons._();

  static const _kFontFam = 'AdvisorIcons';
  static const _kFontPkg = null;

  static const IconData shopping = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData children = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grocery = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beauty = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData culture = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tourism = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wellbeing = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hobby = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cafe = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pets = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData housing = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const iconsMap = {
    1: grocery,
    2: shopping,
    3: culture,
    4: cafe,
    5: health,
    6: beauty,
    7: tourism,
    8: hobby,
    9: housing,
    10: pets,
    11: children,
    12: wellbeing,
    13: money,
    14: money,
    15: money,
    16: money,
    17: money,
    18: money,
    19: money
  };

  static IconData get(int id) {
    return iconsMap[id];
  }
}
